### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by jameslkingsley** [ARCOMM/ARCORE#2]
- [x] Remove fireteam markers
- [x] Improve AI gear
- [x] Allow group markers to be shown to specific sides
- [x] Add flare config patch from [POTATO](https://github.com/BourbonWarfare/POTATO/tree/master/addons/flares)
- [x] Reduce ACRE radio mass
- [x] Add briefing start/end chat commands and diary links
